"""Source-to-lesson coverage map.

Quality-control artifact, not part of the learner-facing course.

Each row is (source, chapter, section, concept, lesson_id) where:

    S1  = Sauer, Numerical Analysis, 3rd ed. (Pearson, 2019)
    S2  = Gupta, Numerical Methods: Fundamentals and Applications (Cambridge, 2019)
    S3  = Trefethen and Bau, Numerical Linear Algebra (the concept map in
          TrefethenBau.md, supplied as the authoritative coverage checklist)
    SUP = Supplementary / Advanced Material, not from any supplied source

lesson_id is the two-digit id defined in lesson_map.py.

Status flags (covered / implemented / experimented / tested / verified) live in
coverage_status.json and start False.
"""

ROWS = [
    # ================================================================ S1 Chapter 0
    ("S1", "0 Fundamentals", "0.1", "Evaluating a polynomial, nested (Horner) form", "01"),
    ("S1", "0 Fundamentals", "0.1", "Operation counting for polynomial evaluation", "08"),
    ("S1", "0 Fundamentals", "0.2", "Decimal to binary conversion", "02"),
    ("S1", "0 Fundamentals", "0.2", "Binary to decimal conversion", "02"),
    ("S1", "0 Fundamentals", "0.3", "IEEE 754 floating point formats (single, double, long double)", "03"),
    ("S1", "0 Fundamentals", "0.3", "Normalized machine representation, left-justified mantissa", "03"),
    ("S1", "0 Fundamentals", "0.3", "Machine epsilon definition", "03"),
    ("S1", "0 Fundamentals", "0.3", "Rounding versus chopping", "03"),
    ("S1", "0 Fundamentals", "0.3", "Addition of floating point numbers", "03"),
    ("S1", "0 Fundamentals", "0.4", "Loss of significance, catastrophic cancellation", "05"),
    ("S1", "0 Fundamentals", "0.4", "Rewriting formulas to avoid cancellation (quadratic formula)", "05"),
    ("S1", "0 Fundamentals", "0.5", "Review of calculus: IVT, MVT, Rolle, Taylor with remainder", "07"),

    # ================================================================ S1 Chapter 1
    ("S1", "1 Solving Equations", "1.1", "Bisection method, bracketing a root", "09"),
    ("S1", "1 Solving Equations", "1.1", "Bisection accuracy bound and iteration count", "09"),
    ("S1", "1 Solving Equations", "1.2", "Fixed points of a function", "10"),
    ("S1", "1 Solving Equations", "1.2", "Geometry of fixed point iteration (cobweb diagram)", "10"),
    ("S1", "1 Solving Equations", "1.2", "Linear convergence of fixed point iteration", "10"),
    ("S1", "1 Solving Equations", "1.2", "Stopping criteria and their failure modes", "10"),
    ("S1", "1 Solving Equations", "1.3", "Forward and backward error", "06"),
    ("S1", "1 Solving Equations", "1.3", "The Wilkinson polynomial", "12"),
    ("S1", "1 Solving Equations", "1.3", "Sensitivity of root finding, condition number of a root", "12"),
    ("S1", "1 Solving Equations", "1.4", "Newton's method derivation", "11"),
    ("S1", "1 Solving Equations", "1.4", "Quadratic convergence of Newton's method", "11"),
    ("S1", "1 Solving Equations", "1.4", "Linear convergence at multiple roots, modified Newton", "11"),
    ("S1", "1 Solving Equations", "1.5", "Secant method and its order of convergence", "11"),
    ("S1", "1 Solving Equations", "1.5", "Secant variants (false position, Illinois, inverse quadratic)", "09"),
    ("S1", "1 Solving Equations", "1.5", "Brent's method", "11"),
    ("S1", "1 Solving Equations", "RC1", "Kinematics of the Stewart platform", "14"),

    # ================================================================ S1 Chapter 2
    ("S1", "2 Systems of Equations", "2.1", "Naive Gaussian elimination", "17"),
    ("S1", "2 Systems of Equations", "2.1", "Operation counts for Gaussian elimination", "17"),
    ("S1", "2 Systems of Equations", "2.2", "Matrix form of Gaussian elimination, LU factorization", "17"),
    ("S1", "2 Systems of Equations", "2.2", "Back substitution with the LU factorization", "17"),
    ("S1", "2 Systems of Equations", "2.2", "Complexity of the LU factorization", "17"),
    ("S1", "2 Systems of Equations", "2.3", "Infinity norm of a vector", "15"),
    ("S1", "2 Systems of Equations", "2.3", "Residual, backward error and forward error for Ax=b", "19"),
    ("S1", "2 Systems of Equations", "2.3", "Error magnification factor and matrix condition number", "19"),
    ("S1", "2 Systems of Equations", "2.3", "Hilbert matrix as an ill-conditioned example", "19"),
    ("S1", "2 Systems of Equations", "2.3", "Swamping", "18"),
    ("S1", "2 Systems of Equations", "2.4", "Partial pivoting", "18"),
    ("S1", "2 Systems of Equations", "2.4", "Permutation matrices", "18"),
    ("S1", "2 Systems of Equations", "2.4", "PA = LU factorization", "18"),
    ("S1", "2 Systems of Equations", "RC2", "The Euler-Bernoulli beam", "19"),
    ("S1", "2 Systems of Equations", "2.5", "Jacobi method", "23"),
    ("S1", "2 Systems of Equations", "2.5", "Gauss-Seidel method and SOR", "23"),
    ("S1", "2 Systems of Equations", "2.5", "Convergence of iterative methods, spectral radius", "23"),
    ("S1", "2 Systems of Equations", "2.5", "Sparse matrix computations", "21"),
    ("S1", "2 Systems of Equations", "2.6", "Symmetric positive definite matrices", "20"),
    ("S1", "2 Systems of Equations", "2.6", "Cholesky factorization", "20"),
    ("S1", "2 Systems of Equations", "2.6", "Conjugate Gradient method, A-inner product, conjugacy", "24"),
    ("S1", "2 Systems of Equations", "2.6", "Preconditioning, Jacobi and SSOR preconditioners", "25"),
    ("S1", "2 Systems of Equations", "2.7", "Multivariate Newton's method and the Jacobian", "14"),
    ("S1", "2 Systems of Equations", "2.7", "Broyden's method", "14"),

    # ================================================================ S1 Chapter 3
    ("S1", "3 Interpolation", "3.1", "Lagrange interpolation", "44"),
    ("S1", "3 Interpolation", "3.1", "Newton's divided differences", "45"),
    ("S1", "3 Interpolation", "3.1", "Uniqueness of the degree-d interpolating polynomial", "44"),
    ("S1", "3 Interpolation", "3.1", "Representing functions by approximating polynomials", "44"),
    ("S1", "3 Interpolation", "3.2", "Interpolation error formula", "46"),
    ("S1", "3 Interpolation", "3.2", "Proof of the Newton form and the error formula", "46"),
    ("S1", "3 Interpolation", "3.2", "Runge phenomenon", "46"),
    ("S1", "3 Interpolation", "3.3", "Chebyshev's theorem on node placement", "47"),
    ("S1", "3 Interpolation", "3.3", "Chebyshev polynomials and their recurrence", "47"),
    ("S1", "3 Interpolation", "3.3", "Change of interval for Chebyshev nodes", "47"),
    ("S1", "3 Interpolation", "3.4", "Cubic spline properties and the tridiagonal system", "51"),
    ("S1", "3 Interpolation", "3.4", "Spline endpoint conditions (natural, clamped, parabolic, not-a-knot)", "51"),
    ("S1", "3 Interpolation", "3.5", "Bezier curves", "52"),
    ("S1", "3 Interpolation", "RC3", "Fonts from Bezier curves", "52"),

    # ================================================================ S1 Chapter 4
    ("S1", "4 Least Squares", "4.1", "Inconsistent systems and the least squares idea", "29"),
    ("S1", "4 Least Squares", "4.1", "Normal equations and projection geometry", "29"),
    ("S1", "4 Least Squares", "4.1", "Fitting models to data", "29"),
    ("S1", "4 Least Squares", "4.1", "Conditioning of least squares, squared condition number", "29"),
    ("S1", "4 Least Squares", "4.2", "Periodic data models", "29"),
    ("S1", "4 Least Squares", "4.2", "Data linearization for exponential and power models", "29"),
    ("S1", "4 Least Squares", "4.3", "Classical Gram-Schmidt orthogonalization and least squares", "30"),
    ("S1", "4 Least Squares", "4.3", "Reduced and full QR factorization", "30"),
    ("S1", "4 Least Squares", "4.3", "Modified Gram-Schmidt and loss of orthogonality", "30"),
    ("S1", "4 Least Squares", "4.3", "Householder reflectors and Householder QR", "31"),
    ("S1", "4 Least Squares", "4.4", "Krylov methods and the Krylov subspace", "26"),
    ("S1", "4 Least Squares", "4.4", "GMRES algorithm", "27"),
    ("S1", "4 Least Squares", "4.4", "Preconditioned GMRES", "27"),
    ("S1", "4 Least Squares", "4.5", "Gauss-Newton method", "34"),
    ("S1", "4 Least Squares", "4.5", "Models with nonlinear parameters", "34"),
    ("S1", "4 Least Squares", "4.5", "Levenberg-Marquardt method", "34"),
    ("S1", "4 Least Squares", "RC4", "GPS, conditioning and nonlinear least squares", "34"),

    # ================================================================ S1 Chapter 5
    ("S1", "5 Differentiation and Integration", "5.1", "Finite difference formulas for derivatives", "61"),
    ("S1", "5 Differentiation and Integration", "5.1", "Rounding versus truncation error, optimal step size", "61"),
    ("S1", "5 Differentiation and Integration", "5.1", "Extrapolation for derivatives", "61"),
    ("S1", "5 Differentiation and Integration", "5.1", "Symbolic differentiation and integration", "61"),
    ("S1", "5 Differentiation and Integration", "5.2", "Trapezoid rule", "62"),
    ("S1", "5 Differentiation and Integration", "5.2", "Simpson's rule", "62"),
    ("S1", "5 Differentiation and Integration", "5.2", "Composite Newton-Cotes formulas", "62"),
    ("S1", "5 Differentiation and Integration", "5.2", "Open Newton-Cotes methods", "62"),
    ("S1", "5 Differentiation and Integration", "5.3", "Romberg integration", "63"),
    ("S1", "5 Differentiation and Integration", "5.4", "Adaptive quadrature", "64"),
    ("S1", "5 Differentiation and Integration", "5.5", "Gaussian quadrature, Legendre nodes and weights", "65"),
    ("S1", "5 Differentiation and Integration", "RC5", "Motion control in computer-aided modeling", "64"),

    # ================================================================ S1 Chapter 6
    ("S1", "6 Ordinary Differential Equations", "6.1", "Initial value problems, Euler's method", "67"),
    ("S1", "6 Ordinary Differential Equations", "6.1", "Existence, uniqueness and continuity, Lipschitz condition", "67"),
    ("S1", "6 Ordinary Differential Equations", "6.1", "First order linear equations", "67"),
    ("S1", "6 Ordinary Differential Equations", "6.2", "Local and global truncation error", "67"),
    ("S1", "6 Ordinary Differential Equations", "6.2", "Explicit trapezoid method", "69"),
    ("S1", "6 Ordinary Differential Equations", "6.2", "Taylor methods for ODEs", "68"),
    ("S1", "6 Ordinary Differential Equations", "6.3", "Systems of ODEs, higher order equations", "73"),
    ("S1", "6 Ordinary Differential Equations", "6.3", "Computer simulation: the pendulum", "73"),
    ("S1", "6 Ordinary Differential Equations", "6.3", "Computer simulation: orbital mechanics", "73"),
    ("S1", "6 Ordinary Differential Equations", "6.4", "The Runge-Kutta family, RK4", "69"),
    ("S1", "6 Ordinary Differential Equations", "6.4", "Computer simulation: Hodgkin-Huxley neuron", "73"),
    ("S1", "6 Ordinary Differential Equations", "6.4", "Computer simulation: Lorenz equations", "73"),
    ("S1", "6 Ordinary Differential Equations", "RC6", "The Tacoma Narrows Bridge", "73"),
    ("S1", "6 Ordinary Differential Equations", "6.5", "Embedded Runge-Kutta pairs", "70"),
    ("S1", "6 Ordinary Differential Equations", "6.5", "Order 4/5 methods (RKF45, Dormand-Prince)", "70"),
    ("S1", "6 Ordinary Differential Equations", "6.6", "Implicit methods and stiff equations", "72"),
    ("S1", "6 Ordinary Differential Equations", "6.7", "Generating multistep methods", "71"),
    ("S1", "6 Ordinary Differential Equations", "6.7", "Explicit multistep methods (Adams-Bashforth)", "71"),
    ("S1", "6 Ordinary Differential Equations", "6.7", "Implicit multistep methods (Adams-Moulton)", "71"),

    # ================================================================ S1 Chapter 7
    ("S1", "7 Boundary Value Problems", "7.1", "Solutions of boundary value problems", "75"),
    ("S1", "7 Boundary Value Problems", "7.1", "Shooting method implementation", "75"),
    ("S1", "7 Boundary Value Problems", "RC7", "Buckling of a circular ring", "75"),
    ("S1", "7 Boundary Value Problems", "7.2", "Finite difference method for linear BVPs", "75"),
    ("S1", "7 Boundary Value Problems", "7.2", "Finite difference method for nonlinear BVPs", "75"),
    ("S1", "7 Boundary Value Problems", "7.3", "Collocation", "76"),
    ("S1", "7 Boundary Value Problems", "7.3", "Finite elements and the Galerkin method", "76"),

    # ================================================================ S1 Chapter 8
    ("S1", "8 Partial Differential Equations", "8.1", "Forward difference method for parabolic equations", "78"),
    ("S1", "8 Partial Differential Equations", "8.1", "Stability analysis of the forward difference method", "79"),
    ("S1", "8 Partial Differential Equations", "8.1", "Backward difference method", "78"),
    ("S1", "8 Partial Differential Equations", "8.1", "Crank-Nicolson method", "78"),
    ("S1", "8 Partial Differential Equations", "8.2", "The wave equation", "81"),
    ("S1", "8 Partial Differential Equations", "8.2", "The CFL condition", "81"),
    ("S1", "8 Partial Differential Equations", "8.3", "Finite difference method for elliptic equations", "82"),
    ("S1", "8 Partial Differential Equations", "RC8", "Heat distribution on a cooling fin", "82"),
    ("S1", "8 Partial Differential Equations", "8.3", "Finite element method for elliptic equations", "82"),
    ("S1", "8 Partial Differential Equations", "8.4", "Implicit Newton solver for nonlinear PDEs", "83"),
    ("S1", "8 Partial Differential Equations", "8.4", "Nonlinear equations in two space dimensions", "83"),

    # ================================================================ S1 Chapter 9
    ("S1", "9 Random Numbers", "9.1", "Pseudo-random numbers, linear congruential generators", "91"),
    ("S1", "9 Random Numbers", "9.1", "Exponential and normal random numbers", "91"),
    ("S1", "9 Random Numbers", "9.2", "Monte Carlo simulation", "92"),
    ("S1", "9 Random Numbers", "9.2", "Power laws for Monte Carlo estimation", "92"),
    ("S1", "9 Random Numbers", "9.2", "Quasi-random numbers (Halton sequences)", "92"),
    ("S1", "9 Random Numbers", "9.3", "Random walks", "93"),
    ("S1", "9 Random Numbers", "9.3", "Continuous Brownian motion", "93"),
    ("S1", "9 Random Numbers", "9.4", "Adding noise to differential equations", "93"),
    ("S1", "9 Random Numbers", "9.4", "Numerical methods for SDEs (Euler-Maruyama, Milstein)", "93"),
    ("S1", "9 Random Numbers", "RC9", "The Black-Scholes formula", "93"),

    # ================================================================ S1 Chapter 10
    ("S1", "10 Trigonometric Interpolation and the FFT", "10.1", "Complex arithmetic and roots of unity", "58"),
    ("S1", "10 Trigonometric Interpolation and the FFT", "10.1", "Discrete Fourier Transform", "58"),
    ("S1", "10 Trigonometric Interpolation and the FFT", "10.1", "Fast Fourier Transform", "59"),
    ("S1", "10 Trigonometric Interpolation and the FFT", "10.2", "DFT Interpolation Theorem", "58"),
    ("S1", "10 Trigonometric Interpolation and the FFT", "10.2", "Efficient evaluation of trigonometric functions", "58"),
    ("S1", "10 Trigonometric Interpolation and the FFT", "10.3", "Orthogonality and interpolation", "58"),
    ("S1", "10 Trigonometric Interpolation and the FFT", "10.3", "Least squares fitting with trigonometric functions", "59"),
    ("S1", "10 Trigonometric Interpolation and the FFT", "10.3", "Sound, noise and filtering", "59"),
    ("S1", "10 Trigonometric Interpolation and the FFT", "RC10", "The Wiener filter", "59"),

    # ================================================================ S1 Chapter 11
    ("S1", "11 Compression", "11.1", "One-dimensional Discrete Cosine Transform", "60"),
    ("S1", "11 Compression", "11.1", "The DCT and least squares approximation", "60"),
    ("S1", "11 Compression", "11.2", "Two-dimensional DCT", "60"),
    ("S1", "11 Compression", "11.2", "Image compression", "60"),
    ("S1", "11 Compression", "11.2", "Quantization", "60"),
    ("S1", "11 Compression", "11.3", "Information theory and coding", "60"),
    ("S1", "11 Compression", "11.3", "Huffman coding for the JPEG format", "60"),
    ("S1", "11 Compression", "11.4", "Modified Discrete Cosine Transform", "60"),
    ("S1", "11 Compression", "11.4", "Bit quantization", "60"),
    ("S1", "11 Compression", "RC11", "A simple audio codec", "60"),

    # ================================================================ S1 Chapter 12
    ("S1", "12 Eigenvalues and Singular Values", "12.1", "Power iteration", "36"),
    ("S1", "12 Eigenvalues and Singular Values", "12.1", "Convergence of power iteration", "36"),
    ("S1", "12 Eigenvalues and Singular Values", "12.1", "Inverse power iteration", "36"),
    ("S1", "12 Eigenvalues and Singular Values", "12.1", "Rayleigh quotient iteration", "36"),
    ("S1", "12 Eigenvalues and Singular Values", "12.2", "Simultaneous iteration and normalized simultaneous iteration", "37"),
    ("S1", "12 Eigenvalues and Singular Values", "12.2", "Real Schur form and the QR algorithm", "37"),
    ("S1", "12 Eigenvalues and Singular Values", "12.2", "Upper Hessenberg form", "37"),
    ("S1", "12 Eigenvalues and Singular Values", "RC12", "How search engines rate page quality (PageRank)", "43"),
    ("S1", "12 Eigenvalues and Singular Values", "12.3", "Geometry of the SVD (unit sphere to hyperellipse)", "41"),
    ("S1", "12 Eigenvalues and Singular Values", "12.3", "Finding the SVD in general", "41"),
    ("S1", "12 Eigenvalues and Singular Values", "12.4", "Properties of the SVD", "41"),
    ("S1", "12 Eigenvalues and Singular Values", "12.4", "Dimension reduction", "43"),
    ("S1", "12 Eigenvalues and Singular Values", "12.4", "Compression with the SVD", "43"),
    ("S1", "12 Eigenvalues and Singular Values", "12.4", "Calculating the SVD, the condition squaring warning", "42"),

    # ================================================================ S1 Chapter 13
    ("S1", "13 Optimization", "13.1", "Golden section search", "85"),
    ("S1", "13 Optimization", "13.1", "Successive parabolic interpolation", "85"),
    ("S1", "13 Optimization", "13.1", "Nelder-Mead search", "85"),
    ("S1", "13 Optimization", "13.2", "Newton's method for optimization", "86"),
    ("S1", "13 Optimization", "13.2", "Steepest descent", "86"),
    ("S1", "13 Optimization", "13.2", "Conjugate gradient search for nonlinear problems", "87"),
    ("S1", "13 Optimization", "RC13", "Molecular conformation and numerical optimization", "87"),

    # ================================================================ S1 Appendices
    ("S1", "Appendix A", "A.1-A.3", "Matrix fundamentals, linear systems, block multiplication", "15"),
    ("S1", "Appendix A", "A.4-A.5", "Eigenvalues and eigenvectors, symmetric matrices", "35"),
    ("S1", "Appendix A", "A.6", "Vector calculus: gradient, Jacobian, Hessian", "84"),
    ("S1", "Appendix B", "B.1-B.7", "Programming environment basics, translated to NumPy conventions", "01"),

    # ================================================================ S2 Chapter 1
    ("S2", "1 Number Systems", "1.2", "Representation of integers in binary, octal and hexadecimal", "02"),
    ("S2", "1 Number Systems", "1.2.1", "Conversion from any base to decimal", "02"),
    ("S2", "1 Number Systems", "1.2.2", "Conversion between binary, octal and hexadecimal", "02"),
    ("S2", "1 Number Systems", "1.2.3", "Conversion from decimal to any other base", "02"),
    ("S2", "1 Number Systems", "1.2.4", "Conversion from one base to any other base", "02"),
    ("S2", "1 Number Systems", "1.3", "Representation of fractions", "02"),

    # ================================================================ S2 Chapter 2
    ("S2", "2 Error Analysis", "2.1", "Absolute, relative and percentage errors", "04"),
    ("S2", "2 Error Analysis", "2.2.1", "Modeling error", "04"),
    ("S2", "2 Error Analysis", "2.2.2", "Inherent error (error in the original data)", "04"),
    ("S2", "2 Error Analysis", "2.2.3", "Blunder", "04"),
    ("S2", "2 Error Analysis", "2.3.1", "Round-off error", "03"),
    ("S2", "2 Error Analysis", "2.3.2", "Overflow and underflow", "03"),
    ("S2", "2 Error Analysis", "2.3.3.1", "Propagated error in arithmetic operations", "04"),
    ("S2", "2 Error Analysis", "2.3.3.2", "Error propagation in a function of one variable", "04"),
    ("S2", "2 Error Analysis", "2.3.3.3", "Error propagation in a function of several variables", "04"),
    ("S2", "2 Error Analysis", "2.3.4", "Truncation error", "04"),
    ("S2", "2 Error Analysis", "2.3.5", "Machine epsilon", "03"),
    ("S2", "2 Error Analysis", "2.3.7", "Loss of significance, condition and stability", "05"),
    ("S2", "2 Error Analysis", "2.4", "How error accumulates over many operations", "04"),

    # ================================================================ S2 Chapter 3
    ("S2", "3 Nonlinear Equations", "3.1", "Polynomial and transcendental equations", "09"),
    ("S2", "3 Nonlinear Equations", "3.2", "Direct, graphical, trial-and-error and iterative approaches", "09"),
    ("S2", "3 Nonlinear Equations", "3.3", "Bisection (Bolzano, interval halving) method", "09"),
    ("S2", "3 Nonlinear Equations", "3.4", "Fixed-point (successive approximation) method", "10"),
    ("S2", "3 Nonlinear Equations", "3.5", "Newton-Raphson method", "11"),
    ("S2", "3 Nonlinear Equations", "3.6", "Regula falsi (false position) method", "09"),
    ("S2", "3 Nonlinear Equations", "3.7", "Secant method", "11"),
    ("S2", "3 Nonlinear Equations", "3.8.1-3.8.5", "Convergence proofs for all five root-finding methods", "12"),
    ("S2", "3 Nonlinear Equations", "3.9.1-3.9.5", "Order of convergence for all five methods", "12"),
    ("S2", "3 Nonlinear Equations", "3.10", "Muller method", "11"),
    ("S2", "3 Nonlinear Equations", "3.11", "Chebyshev method (third order)", "11"),
    ("S2", "3 Nonlinear Equations", "3.12", "Aitken delta-squared acceleration", "10"),
    ("S2", "3 Nonlinear Equations", "3.13", "Summary and comparison of root-finding methods", "12"),

    # ================================================================ S2 Chapter 4
    ("S2", "4 Nonlinear Systems and Polynomials", "4.1", "Fixed-point method for systems", "14"),
    ("S2", "4 Nonlinear Systems and Polynomials", "4.2", "Seidel iteration method for systems", "14"),
    ("S2", "4 Nonlinear Systems and Polynomials", "4.3", "Newton-Raphson method for systems", "14"),
    ("S2", "4 Nonlinear Systems and Polynomials", "4.4", "Complex roots", "13"),
    ("S2", "4 Nonlinear Systems and Polynomials", "4.5.1", "Descartes rule of signs", "13"),
    ("S2", "4 Nonlinear Systems and Polynomials", "4.5.2", "Sturm sequence for counting real roots", "13"),
    ("S2", "4 Nonlinear Systems and Polynomials", "4.6", "Birge-Vieta (Horner) method", "13"),
    ("S2", "4 Nonlinear Systems and Polynomials", "4.7", "Lin-Bairstow method for quadratic factors", "13"),
    ("S2", "4 Nonlinear Systems and Polynomials", "4.8", "Graeffe root squaring method", "13"),

    # ================================================================ S2 Chapter 5
    ("S2", "5 Systems of Linear Equations", "5.2", "Cramer rule and why it is impractical", "17"),
    ("S2", "5 Systems of Linear Equations", "5.3", "Matrix inversion method", "17"),
    ("S2", "5 Systems of Linear Equations", "5.4.1", "Doolittle LU method", "17"),
    ("S2", "5 Systems of Linear Equations", "5.4.2", "Crout LU method", "17"),
    ("S2", "5 Systems of Linear Equations", "5.4.3", "Cholesky method", "20"),
    ("S2", "5 Systems of Linear Equations", "5.5", "Gauss elimination method", "17"),
    ("S2", "5 Systems of Linear Equations", "5.5.1", "Operational counts for Gauss elimination", "17"),
    ("S2", "5 Systems of Linear Equations", "5.5.2", "Thomas algorithm for tridiagonal systems", "21"),
    ("S2", "5 Systems of Linear Equations", "5.6", "Gauss-Jordan method", "17"),
    ("S2", "5 Systems of Linear Equations", "5.7", "Comparison of direct methods", "18"),
    ("S2", "5 Systems of Linear Equations", "5.8", "Pivoting strategies", "18"),
    ("S2", "5 Systems of Linear Equations", "5.9-5.10", "Iterative methods and the Jacobi method", "23"),
    ("S2", "5 Systems of Linear Equations", "5.11", "Gauss-Seidel method", "23"),
    ("S2", "5 Systems of Linear Equations", "5.12", "Relaxation method (SOR)", "23"),
    ("S2", "5 Systems of Linear Equations", "5.13", "Convergence criteria for iterative methods", "23"),
    ("S2", "5 Systems of Linear Equations", "5.14", "Matrix forms and convergence of iterative methods", "23"),
    ("S2", "5 Systems of Linear Equations", "5.16", "Applications of linear systems", "19"),

    # ================================================================ S2 Chapter 6
    ("S2", "6 Eigenvalues and Eigenvectors", "6.2", "Eigenvalues and eigenvectors, real and complex", "35"),
    ("S2", "6 Eigenvalues and Eigenvectors", "6.2.3-6.2.4", "Distinct and repeated eigenvalues, independent and dependent eigenvectors", "35"),
    ("S2", "6 Eigenvalues and Eigenvectors", "6.3.1", "Gerschgorin theorem", "35"),
    ("S2", "6 Eigenvalues and Eigenvectors", "6.3.2", "Brauer (Cassini oval) theorem", "35"),
    ("S2", "6 Eigenvalues and Eigenvectors", "6.4", "Rayleigh power method", "36"),
    ("S2", "6 Eigenvalues and Eigenvectors", "6.4.1", "Inverse power method", "36"),
    ("S2", "6 Eigenvalues and Eigenvectors", "6.4.2", "Shifted power method", "36"),
    ("S2", "6 Eigenvalues and Eigenvectors", "6.5", "Rutishauser (LR) decomposition method", "37"),

    # ================================================================ S2 Chapter 7
    ("S2", "7 Symmetric Eigenproblem", "7.1.1", "Similarity transformations", "35"),
    ("S2", "7 Symmetric Eigenproblem", "7.1.2", "Orthogonal transformations", "38"),
    ("S2", "7 Symmetric Eigenproblem", "7.2", "Jacobi rotation method", "38"),
    ("S2", "7 Symmetric Eigenproblem", "7.3", "Sturm sequence for real symmetric tridiagonal matrices", "38"),
    ("S2", "7 Symmetric Eigenproblem", "7.4", "Givens method (tridiagonalization by rotations)", "38"),
    ("S2", "7 Symmetric Eigenproblem", "7.5", "Householder method (tridiagonalization by reflections)", "38"),

    # ================================================================ S2 Chapter 8
    ("S2", "8 Interpolation", "8.2.1", "Power form of a polynomial", "44"),
    ("S2", "8 Interpolation", "8.2.2", "Shifted power form", "44"),
    ("S2", "8 Interpolation", "8.2.3", "Newton form", "44"),
    ("S2", "8 Interpolation", "8.2.4", "Nested Newton form", "44"),
    ("S2", "8 Interpolation", "8.2.5", "Recursive algorithm for the nested Newton form", "44"),
    ("S2", "8 Interpolation", "8.2.6", "Change of center in the Newton form", "44"),
    ("S2", "8 Interpolation", "8.3", "Lagrange method", "44"),
    ("S2", "8 Interpolation", "8.4", "Newton divided difference method", "45"),
    ("S2", "8 Interpolation", "8.4.1", "Proof for higher order divided differences", "45"),
    ("S2", "8 Interpolation", "8.4.2", "Advantages of divided differences over Lagrange", "45"),
    ("S2", "8 Interpolation", "8.4.3", "Properties of divided differences", "45"),
    ("S2", "8 Interpolation", "8.5", "Error in the interpolating polynomial", "46"),
    ("S2", "8 Interpolation", "8.7", "Hermite interpolation", "50"),
    ("S2", "8 Interpolation", "8.8", "Piecewise interpolation", "50"),
    ("S2", "8 Interpolation", "8.9", "Weierstrass approximation theorem", "54"),

    # ================================================================ S2 Chapter 9
    ("S2", "9 Finite Operators", "9.2.1", "Forward difference operator", "48"),
    ("S2", "9 Finite Operators", "9.2.2", "Backward difference operator", "48"),
    ("S2", "9 Finite Operators", "9.2.3", "Central difference operator", "48"),
    ("S2", "9 Finite Operators", "9.3.1", "Mean (average) operator", "48"),
    ("S2", "9 Finite Operators", "9.3.2", "Shift operator E", "48"),
    ("S2", "9 Finite Operators", "9.3.3", "Differential operator D", "48"),
    ("S2", "9 Finite Operators", "9.4.1", "Linearity and commutativity of finite operators", "48"),
    ("S2", "9 Finite Operators", "9.4.2", "Interrelations of the finite operators", "48"),
    ("S2", "9 Finite Operators", "9.5", "Operators applied to standard functions", "48"),
    ("S2", "9 Finite Operators", "9.6", "Newton divided differences and other finite differences", "48"),
    ("S2", "9 Finite Operators", "9.7", "Finite difference tables and error propagation in them", "48"),

    # ================================================================ S2 Chapter 10
    ("S2", "10 Equal Interval Interpolation", "10.1", "Gregory-Newton forward difference formula and its error", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.2", "Gregory-Newton backward difference formula and its error", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.3", "Central difference formulas", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.4", "Gauss forward central difference formula", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.5", "Gauss backward central difference formula", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.6", "Stirling formula", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.7", "Bessel formula", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.8", "Everett formula", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.9", "Steffensen formula", "49"),
    ("S2", "10 Equal Interval Interpolation", "10.10.1", "Lagrange bivariate interpolation", "53"),
    ("S2", "10 Equal Interval Interpolation", "10.10.2", "Newton bivariate interpolation for equi-spaced points", "53"),

    # ================================================================ S2 Chapter 11
    ("S2", "11 Splines and Curve Fitting", "11.2.1", "Cubic spline interpolation", "51"),
    ("S2", "11 Splines and Curve Fitting", "11.2.2", "Cubic spline for equi-spaced points", "51"),
    ("S2", "11 Splines and Curve Fitting", "11.3", "Bezier curve", "52"),
    ("S2", "11 Splines and Curve Fitting", "11.4", "B-spline curve", "52"),
    ("S2", "11 Splines and Curve Fitting", "11.5.1", "Straight line least squares fitting", "29"),
    ("S2", "11 Splines and Curve Fitting", "11.5.2", "Nonlinear curve fitting by linearization", "29"),
    ("S2", "11 Splines and Curve Fitting", "11.5.3", "Quadratic curve fitting", "29"),
    ("S2", "11 Splines and Curve Fitting", "11.6", "Chebyshev polynomial approximation", "56"),
    ("S2", "11 Splines and Curve Fitting", "11.7", "Pade approximation by rational functions", "57"),

    # ================================================================ S2 Chapter 12
    ("S2", "12 Numerical Differentiation", "12.2", "Differentiation formulas derived from interpolation", "61"),
    ("S2", "12 Numerical Differentiation", "12.2", "Summary table of differentiation formulas", "61"),

    # ================================================================ S2 Chapter 13
    ("S2", "13 Numerical Integration", "13.1", "Newton-Cotes quadrature derived via Lagrange", "62"),
    ("S2", "13 Numerical Integration", "13.1.1", "Trapezoidal rule", "62"),
    ("S2", "13 Numerical Integration", "13.1.2", "Simpson 1/3 rule", "62"),
    ("S2", "13 Numerical Integration", "13.1.3", "Simpson 3/8 rule", "62"),
    ("S2", "13 Numerical Integration", "13.1.4", "Boole rule", "62"),
    ("S2", "13 Numerical Integration", "13.1.5", "Weddle rule", "62"),
    ("S2", "13 Numerical Integration", "13.2", "Composite Newton-Cotes rules", "62"),
    ("S2", "13 Numerical Integration", "13.3", "Error terms for all Newton-Cotes rules", "62"),
    ("S2", "13 Numerical Integration", "13.4.1", "Gauss-Legendre formula", "65"),
    ("S2", "13 Numerical Integration", "13.4.2", "Gauss-Chebyshev formula", "65"),
    ("S2", "13 Numerical Integration", "13.4.3", "Gauss-Laguerre formula", "65"),
    ("S2", "13 Numerical Integration", "13.4.4", "Gauss-Hermite formula", "65"),
    ("S2", "13 Numerical Integration", "13.5", "Euler-Maclaurin formula", "63"),
    ("S2", "13 Numerical Integration", "13.6", "Richardson extrapolation", "63"),
    ("S2", "13 Numerical Integration", "13.7", "Romberg integration", "63"),
    ("S2", "13 Numerical Integration", "13.8", "Double integrals by trapezoidal and Simpson rules", "66"),

    # ================================================================ S2 Chapter 14
    ("S2", "14 First Order ODE IVPs", "14.1", "Classification and terminology of differential equations", "67"),
    ("S2", "14 First Order ODE IVPs", "14.1.8", "Existence and uniqueness of solutions", "67"),
    ("S2", "14 First Order ODE IVPs", "14.2", "Picard method of successive approximations", "68"),
    ("S2", "14 First Order ODE IVPs", "14.3", "Taylor series method", "68"),
    ("S2", "14 First Order ODE IVPs", "14.4", "Euler method", "67"),
    ("S2", "14 First Order ODE IVPs", "14.5", "Modified and improved Euler (Heun) method", "69"),
    ("S2", "14 First Order ODE IVPs", "14.6", "Runge-Kutta methods", "69"),
    ("S2", "14 First Order ODE IVPs", "14.7", "Milne (Milne-Simpson) method", "71"),
    ("S2", "14 First Order ODE IVPs", "14.8", "Adams-Bashforth predictor and Adams-Moulton corrector", "71"),
    ("S2", "14 First Order ODE IVPs", "14.9", "Errors in numerical methods for ODEs", "67"),
    ("S2", "14 First Order ODE IVPs", "14.10", "Order and stability of numerical methods", "72"),
    ("S2", "14 First Order ODE IVPs", "14.11", "Stability analysis of the linear system y-prime = Ay", "72"),
    ("S2", "14 First Order ODE IVPs", "14.12", "Backward Euler method", "72"),

    # ================================================================ S2 Chapter 15
    ("S2", "15 ODE Systems and BVPs", "15.1-15.4", "Picard, Taylor, Euler and RK4 for systems of ODEs", "73"),
    ("S2", "15 ODE Systems and BVPs", "15.5", "Shooting method for boundary value problems", "75"),
    ("S2", "15 ODE Systems and BVPs", "15.6.1", "Finite difference approximations for first derivatives", "61"),
    ("S2", "15 ODE Systems and BVPs", "15.6.2", "Finite difference approximations for second derivatives", "61"),
    ("S2", "15 ODE Systems and BVPs", "15.7", "Finite difference method for boundary value problems", "75"),
    ("S2", "15 ODE Systems and BVPs", "15.8", "Finite difference approximations for unequal intervals", "75"),

    # ================================================================ S2 Chapter 16
    ("S2", "16 Partial Differential Equations", "16.1", "Classification of second-order quasi-linear PDEs", "77"),
    ("S2", "16 Partial Differential Equations", "16.2", "Initial and boundary conditions", "77"),
    ("S2", "16 Partial Differential Equations", "16.3", "Finite difference approximations for partial derivatives", "77"),
    ("S2", "16 Partial Differential Equations", "16.4.1", "Bender-Schmidt explicit scheme", "78"),
    ("S2", "16 Partial Differential Equations", "16.4.2", "Crank-Nicolson scheme", "78"),
    ("S2", "16 Partial Differential Equations", "16.4.3", "General implicit (weighted) scheme", "78"),
    ("S2", "16 Partial Differential Equations", "16.4.4", "Richardson scheme and its instability", "78"),
    ("S2", "16 Partial Differential Equations", "16.4.5", "Du-Fort and Frankel scheme", "78"),
    ("S2", "16 Partial Differential Equations", "16.5.1-16.5.3", "Consistency, convergence and order of a scheme", "79"),
    ("S2", "16 Partial Differential Equations", "16.5.4", "Stability of a finite difference scheme", "79"),
    ("S2", "16 Partial Differential Equations", "16.5.5-16.5.6", "Matrix method for stability (explicit and Crank-Nicolson)", "79"),
    ("S2", "16 Partial Differential Equations", "16.5.7-16.5.8", "Von Neumann method for stability (explicit and Crank-Nicolson)", "79"),
    ("S2", "16 Partial Differential Equations", "16.6.1-16.6.2", "Two dimensional heat conduction, explicit and CN schemes", "80"),
    ("S2", "16 Partial Differential Equations", "16.6.3", "Alternating Direction Implicit (ADI) scheme", "80"),
    ("S2", "16 Partial Differential Equations", "16.7.1", "Laplace equation by finite differences", "82"),
    ("S2", "16 Partial Differential Equations", "16.7.2", "Poisson equation by finite differences", "82"),
    ("S2", "16 Partial Differential Equations", "16.8.1", "Wave equation, explicit scheme", "81"),
    ("S2", "16 Partial Differential Equations", "16.8.2", "Wave equation, implicit scheme", "81"),
    ("S2", "16 Partial Differential Equations", "16.9", "Building your own finite difference scheme", "79"),

    # ================================================================ S2 Appendices
    ("S2", "Appendix A", "A", "Comparison of analytical and numerical techniques", "01"),
    ("S2", "Appendix B", "B", "Numerical techniques and the computer", "01"),
    ("S2", "Appendix C", "C", "Taylor series reference", "07"),
    ("S2", "Appendix D", "D", "Linear and nonlinear problems", "01"),

    # ================================================================ Supplementary
    ("S3", "L3", "L3", "Vector p-norms, norm axioms, equivalence of norms", "15"),
    ("S3", "L3", "L3", "Induced (operator) matrix norms, Frobenius norm, submultiplicativity", "15"),
    ("S3", "L3", "L3", "Spectral radius versus matrix norm", "15"),
    ("S3", "L13", "L13", "The fl axiom model of floating point arithmetic", "03"),
    ("S3", "L14", "L14", "Formal definition of backward stability and mixed stability", "06"),
    ("SUP", "-", "-", "Compensated (Kahan) summation", "05"),
    ("SUP", "-", "-", "Neumaier summation, fixing Kahan's weak case", "05"),
    ("SUP", "-", "-", "Pairwise summation and its log n error bound", "05"),
    ("SUP", "-", "-", "Sterbenz lemma: when subtraction is exact", "05"),
    ("SUP", "-", "-", "Rewriting formulas to remove cancellation (conjugate, half angle)", "05"),
    ("SUP", "-", "-", "Measuring observed order of convergence numerically", "07"),
    ("SUP", "-", "-", "Flop counting, memory cost and BLAS levels 1, 2 and 3", "08"),
    ("SUP", "-", "-", "Why flop counts alone mislead: memory layout and blocking", "08"),
    ("SUP", "-", "-", "Companion matrix approach to polynomial roots", "13"),
    ("SUP", "-", "-", "Damped Newton and line search for nonlinear systems", "14"),
    ("S3", "L21, L22", "L21, L22", "Growth factor and the theory behind pivoting", "18"),
    ("SUP", "-", "-", "LDL-transpose factorization", "20"),
    ("SUP", "-", "-", "Sparse storage formats (CSR, CSC, COO), fill-in and reordering", "21"),
    ("SUP", "-", "-", "Condition number estimation without forming the inverse", "22"),
    ("SUP", "-", "-", "Iterative refinement and mixed precision refinement", "22"),
    ("S3", "L40", "L40", "Incomplete Cholesky preconditioner", "25"),
    ("S3", "L33", "L33", "Arnoldi iteration stated as its own algorithm", "26"),
    ("S3", "L36", "L36", "Lanczos iteration and loss of orthogonality", "26"),
    ("S3", "L34", "L34", "Ritz values and Krylov convergence intuition", "26"),
    ("S3", "L35, L39", "L35, L39", "Restarted GMRES, MINRES and BiCGSTAB", "27"),
    ("SUP", "-", "-", "Multigrid: smoothing, coarse grid correction and the V-cycle", "28"),
    ("S3", "L35", "L35", "Givens rotations for QR of Hessenberg matrices", "31"),
    ("S3", "L4, L11", "L4, L11", "Moore-Penrose pseudoinverse and rank-deficient least squares", "32"),
    ("SUP", "-", "-", "Tikhonov regularization and the L-curve", "32"),
    ("SUP", "-", "-", "QR with column pivoting and numerical rank", "33"),
    ("SUP", "-", "-", "Total least squares via the SVD", "33"),
    ("S3", "L24", "L24", "Bauer-Fike theorem and eigenvalue conditioning", "35"),
    ("S3", "L24, L29", "L24, L29", "Schur decomposition and its existence", "35"),
    ("SUP", "-", "-", "Divide and conquer for the symmetric tridiagonal eigenproblem", "38"),
    ("SUP", "-", "-", "Lanczos and Arnoldi as eigenvalue solvers, implicit restarting", "39"),
    ("SUP", "-", "-", "Generalized eigenvalue problem, Cholesky reduction and the QZ idea", "40"),
    ("S3", "L31", "L31", "Golub-Kahan bidiagonalization", "42"),
    ("S3", "L31", "L31", "One-sided Jacobi SVD", "42"),
    ("S3", "L5", "L5", "Eckart-Young-Mirsky theorem", "43"),
    ("SUP", "-", "-", "Randomized range finder and randomized SVD", "43"),
    ("SUP", "-", "-", "Conditioning of the Vandermonde matrix", "44"),
    ("SUP", "-", "-", "Barycentric form of Lagrange interpolation", "44"),
    ("SUP", "-", "-", "Lebesgue constant and the near-minimax property of Chebyshev nodes", "47"),
    ("SUP", "-", "-", "de Casteljau algorithm and B-spline basis functions", "52"),
    ("SUP", "-", "-", "Curse of dimensionality in multivariate interpolation", "53"),
    ("SUP", "-", "-", "Norms on function spaces and existence of best approximations", "54"),
    ("SUP", "-", "-", "Minimax versus least squares approximation, equioscillation", "54"),
    ("SUP", "-", "-", "Gram-Schmidt on functions and three-term recurrences", "55"),
    ("SUP", "-", "-", "Legendre, Chebyshev, Laguerre and Hermite polynomial families", "55"),
    ("SUP", "-", "-", "Radix-2 FFT implemented from scratch", "59"),
    ("SUP", "-", "-", "Complex-step differentiation", "61"),
    ("S3", "L37", "L37", "Golub-Welsch algorithm for quadrature nodes and weights", "65"),
    ("SUP", "-", "-", "Improper integrals, variable transformation and singularity handling", "66"),
    ("SUP", "-", "-", "Butcher tableau notation and Runge-Kutta order conditions", "69"),
    ("SUP", "-", "-", "Root condition, zero-stability and the Dahlquist barriers", "71"),
    ("SUP", "-", "-", "Regions of absolute stability, A-stability and L-stability", "72"),
    ("SUP", "-", "-", "Symplectic Euler and Stormer-Verlet, energy behaviour over long times", "74"),
    ("SUP", "-", "-", "Lax equivalence theorem", "79"),
    ("SUP", "-", "-", "Method of lines linking PDEs to ODE solvers", "83"),
    ("SUP", "-", "-", "Optimality conditions, convexity and the Hessian test", "84"),
    ("SUP", "-", "-", "Conditioning of an optimization problem", "84"),
    ("SUP", "-", "-", "Wolfe conditions and backtracking line search", "86"),
    ("SUP", "-", "-", "Secant condition, BFGS and L-BFGS", "87"),
    ("SUP", "-", "-", "Trust region methods", "87"),
    ("SUP", "-", "-", "Lagrange multipliers and the KKT conditions", "88"),
    ("SUP", "-", "-", "Penalty, barrier and projected gradient methods", "88"),
    ("SUP", "-", "-", "Mersenne Twister and PCG64 generators, statistical tests", "91"),
    ("SUP", "-", "-", "Variance reduction: antithetic variates and control variates", "92"),
    ("SUP", "-", "-", "PCA as a truncated SVD, whitening", "94"),
    ("SUP", "-", "-", "Ridge regression as regularized least squares", "94"),
    ("SUP", "-", "-", "Low-rank adaptation as a low-rank matrix factorization", "94"),
    ("SUP", "-", "-", "Gradient descent as an ODE discretization", "95"),
    ("SUP", "-", "-", "Stochastic and minibatch gradient descent, and gradient noise", "89"),
    ("SUP", "-", "-", "Momentum, Nesterov acceleration and the heavy ball method", "89"),
    ("SUP", "-", "-", "Adaptive step sizes: AdaGrad, RMSProp, Adam and AdamW", "89"),
    ("SUP", "-", "-", "Learning rate schedules and the convergence rate of SGD", "89"),
    ("SUP", "-", "-", "The proximal operator and proximal gradient descent", "90"),
    ("SUP", "-", "-", "ISTA and FISTA acceleration for composite problems", "90"),
    ("SUP", "-", "-", "L1 regularization, LASSO and the soft thresholding operator", "90"),
    ("SUP", "-", "-", "Sharp and flat minima, batch size and generalization", "95"),
    ("SUP", "-", "-", "Natural gradient and Gauss-Newton in machine learning", "95"),
    ("SUP", "-", "-", "float16 and bfloat16, exponent and mantissa trade-offs", "96"),
    ("SUP", "-", "-", "The logsumexp trick and numerically stable softmax", "96"),
    ("SUP", "-", "-", "Loss scaling and higher-precision accumulation", "96"),
    ("SUP", "-", "-", "Non-determinism from non-associative floating point reduction", "96"),
    ("SUP", "-", "-", "Forward mode automatic differentiation with dual numbers", "97"),
    ("SUP", "-", "-", "Reverse mode automatic differentiation with a tape", "97"),
    ("SUP", "-", "-", "Cost of automatic differentiation versus finite differences", "97"),
    ("SUP", "-", "-", "Inverse problems and regularization", "98"),
    ("SUP", "-", "-", "Physics-informed neural networks viewed as collocation", "98"),
    ("SUP", "-", "-", "Neural ODEs", "98"),
    ("SUP", "-", "-", "Krylov and low-rank methods inside large-scale learning", "98"),

    # ================================================================ S3 Trefethen and Bau
    # Concepts with no home before the integration audit, plus the specific pieces the
    # audit found missing from lessons that otherwise cover their lecture.

    ("S3", "L2 Orthogonal Vectors and Matrices", "L2", "Inner products, orthogonal and orthonormal vectors", "16"),
    ("S3", "L2 Orthogonal Vectors and Matrices", "L2", "Orthonormal bases and expansion of a vector in one", "16"),
    ("S3", "L2 Orthogonal Vectors and Matrices", "L2", "Orthogonal and unitary matrices", "16"),
    ("S3", "L2 Orthogonal Vectors and Matrices", "L2", "Preservation of the Euclidean norm, and why kappa_2(Q) = 1", "16"),
    ("S3", "L2 Orthogonal Vectors and Matrices", "L2", "Orthogonal changes of coordinates, rotation and reflection geometry", "16"),
    ("S3", "L2 Orthogonal Vectors and Matrices", "L2", "Why orthogonality is the foundation of numerically stable algorithms", "16"),
    ("S3", "L6 Projectors", "L6", "Projectors and idempotence, P squared equals P", "16"),
    ("S3", "L6 Projectors", "L6", "Complementary projectors I - P", "16"),
    ("S3", "L6 Projectors", "L6", "Orthogonal projectors, P conjugate-transpose equals P", "16"),
    ("S3", "L6 Projectors", "L6", "Projection onto the range of an orthonormal basis, P = QQ*", "16"),
    ("S3", "L6 Projectors", "L6", "Rank-one projectors qq* and I - qq*", "16"),
    ("S3", "L6 Projectors", "L6", "Projection error and orthogonality of the residual to the subspace", "16"),
    ("S3", "L6 Projectors", "L6", "Oblique versus orthogonal projection, and the norm of a projector", "16"),
    ("S3", "L1 Matrix-Vector Multiplication", "L1", "Ax as a linear combination of the columns of A", "15"),
    ("S3", "L1 Matrix-Vector Multiplication", "L1", "Matrix product read column by column, and the outer product view", "15"),
    ("S3", "L3 Norms", "L3", "Norm-based error bounds as a working tool", "15"),
    ("S3", "L12 Conditioning", "L12", "Absolute condition number, as distinct from relative", "06"),
    ("S3", "L15 More on Stability", "L15", "A worked backward error analysis carried through the fl model", "06"),
    ("S3", "L17 Stability of Back Substitution", "L17", "Backward stability of back substitution, componentwise", "17"),
    ("S3", "L17 Stability of Back Substitution", "L17", "Why triangular systems solve more accurately than kappa predicts", "17"),
    ("S3", "L22 Stability of Gaussian Elimination", "L22", "Worst case growth versus growth observed in practice", "18"),
    ("S3", "L25 Overview of Eigenvalue Algorithms", "L25", "Why no finite algorithm for eigenvalues exists (Abel and Galois)", "35"),
    ("S3", "L25 Overview of Eigenvalue Algorithms", "L25", "Roadmap of eigenvalue algorithms and what each one is for", "35"),
    ("S3", "L27 Rayleigh Quotient", "L27", "The Rayleigh quotient is stationary at an eigenvector, hence second order accurate", "36"),
    ("S3", "L33 Arnoldi Iteration", "L33", "The Arnoldi relation AQ_m = Q_(m+1) H_m, stated and verified", "26"),
    ("S3", "L36 Lanczos Iteration", "L36", "Ghost eigenvalues from lost orthogonality", "26"),
    ("S3", "L36 Lanczos Iteration", "L36", "Reorthogonalization strategies: none, selective, full", "26"),
    ("S3", "L35 GMRES", "L35", "Stagnation of GMRES", "27"),
    ("S3", "L35 GMRES", "L35", "Why eigenvalues do not determine GMRES convergence for nonnormal matrices", "27"),
    ("S3", "L39 Biorthogonalization", "L39", "Two-sided Lanczos and biorthogonal Krylov bases", "27"),
    ("S3", "L39 Biorthogonalization", "L39", "BiCG, the short recurrence, and breakdown as its price", "27"),
    ("S3", "L38 Conjugate Gradients", "L38", "CG and Lanczos are the same recurrence", "24"),
    ("S3", "L38 Conjugate Gradients", "L38", "Finite precision destroys the finite termination property", "24"),
    ("S3", "L40 Preconditioning", "L40", "Left, right and split preconditioning as distinct operations", "25"),
    ("S3", "L40 Preconditioning", "L40", "Eigenvalue clustering, not condition number, is the real goal", "25"),
    ("S3", "L32 Overview of Iterative Methods", "L32", "The direct versus iterative decision, driven by size, sparsity and accuracy", "23"),
    ("S3", "L7 QR Factorization", "L7", "QR expressed through projectors, and uniqueness conditions", "30"),
    ("S3", "L8 Gram-Schmidt", "L8", "Why classical Gram-Schmidt loses orthogonality and modified does not", "30"),
    ("S3", "L8 Gram-Schmidt", "L8", "Triangular orthogonalization versus orthogonal triangularization", "30"),
    ("S3", "L10 Householder", "L10", "Reflector construction and the reflection geometry", "31"),
    ("S3", "L10 Householder", "L10", "The sign choice that avoids cancellation", "31"),
    ("S3", "L10 Householder", "L10", "Storing Q as reflectors instead of forming it", "31"),
    ("S3", "L16 Stability of Householder", "L16", "Backward stability of Householder QR, stated and verified", "31"),
    ("S3", "L16 Stability of Householder", "L16", "Accurate product QR despite inaccurate Q, and why that is enough", "31"),
    ("S3", "L11 Least Squares", "L11", "Least squares as orthogonal projection, P = A(A*A)^-1 A*", "29"),
    ("S3", "L18 Conditioning of Least Squares", "L18", "The four least squares condition numbers", "32"),
    ("S3", "L18 Conditioning of Least Squares", "L18", "The angle between b and the range of A, and its role", "32"),
    ("S3", "L19 Stability of Least Squares Algorithms", "L19", "Why forming A*A squares the condition number", "32"),
    ("S3", "L19 Stability of Least Squares Algorithms", "L19", "Stability comparison of normal equations, QR and SVD", "32"),
    ("S3", "L34 How Arnoldi Locates Eigenvalues", "L34", "The Rayleigh-Ritz procedure as a projection method", "39"),
    ("S3", "L34 How Arnoldi Locates Eigenvalues", "L34", "Ritz residuals as a stopping test, and which eigenvalues converge first", "39"),
    ("S3", "L4 Singular Value Decomposition", "L4", "Conditioning through singular values, kappa_2 = sigma_1/sigma_n derived", "41"),
    ("S3", "L4 Singular Value Decomposition", "L4", "Minimum-norm solutions via the pseudoinverse", "41"),
    ("S3", "L5 More on the SVD", "L5", "Singular value perturbation and the Weyl inequalities", "43"),
    ("S3", "L37 Lanczos to Gauss Quadrature", "L37", "The Lanczos tridiagonal matrix is the Jacobi matrix of orthogonal polynomials", "65"),
    ("S3", "L37 Lanczos to Gauss Quadrature", "L37", "Gauss nodes are eigenvalues, weights are squared eigenvector components", "65"),

    ("SUP", "-", "-", "Matrix-free operators: Krylov methods need only a matvec", "26"),
    ("SUP", "-", "-", "Sketching for least squares", "43"),
]

SOURCE_NAMES = {
    "S1": "Sauer, Numerical Analysis, 3rd ed. (Pearson, 2019)",
    "S2": "Gupta, Numerical Methods: Fundamentals and Applications (Cambridge, 2019)",
    "S3": "Trefethen and Bau, Numerical Linear Algebra (concept map, TrefethenBau.md)",
    "SUP": "Supplementary / Advanced Material (not from any supplied source)",
}
